global:
  logging: info
  server_port: 45000
  threshold: 2
  db_path: "mongodb+srv://lbackup887:<password>@twinearbitrager.zvxjk.mongodb.net/?retryWrites=true&w=majority&appName=TwineArbitrager"
  balance_check_interval: 10
elf:
  sp1: /home/lilixac/twine/arbitrager/assets/elf/riscv32im-succinct-zkvm-elf
  risc0: 
  dummy: 
provers:
  identifier1:
      prover_ip: http://127.0.0.1:50001
      prover_type: sp1
  identifier2:
      prover_ip: http://127.0.0.1:50002
      prover_type: sp1
  identifier3:
      prover_ip: http://127.0.0.1:50003
      prover_type: sp1
l1s:
  bnb:
      type: evm
      balance_threshold: "10.5" # eth
      contract: 0x32400084c286cf3e17e7b677ea9583e60a000324
      rpc: http://127.0.0.1:8555
      private_key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
  ethereum:
      type: evm
      balance_threshold: "10" # eth
      contract: 0x32400084c286cf3e17e7b677ea9583e60a000324
      rpc: http://127.0.0.1:8545
      private_key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80