name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t --build-arg GITHUB_TOKEN=${{ secrets.PAT_TOKEN }} --build-arg ENV=develop ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:develop .

    # Push the Docker image
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:develop 
